/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil/router";
export { MatchResults, RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppBlog {
        "match": MatchResults;
    }
    interface AppBlogPost {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface AppDevtools {
        "blogList": [];
        "blogPost": {};
        "page": string;
    }
    interface AppFooter {
        "entries": {};
        "footer": {};
    }
    interface AppHeader {
        "entries": {};
        "header": {};
    }
    interface AppHome {
        "history": RouterHistory;
    }
    interface AppNotFound {
    }
    interface AppPage {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppBlogElement extends Components.AppBlog, HTMLStencilElement {
    }
    var HTMLAppBlogElement: {
        prototype: HTMLAppBlogElement;
        new (): HTMLAppBlogElement;
    };
    interface HTMLAppBlogPostElement extends Components.AppBlogPost, HTMLStencilElement {
    }
    var HTMLAppBlogPostElement: {
        prototype: HTMLAppBlogPostElement;
        new (): HTMLAppBlogPostElement;
    };
    interface HTMLAppDevtoolsElement extends Components.AppDevtools, HTMLStencilElement {
    }
    var HTMLAppDevtoolsElement: {
        prototype: HTMLAppDevtoolsElement;
        new (): HTMLAppDevtoolsElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppNotFoundElement extends Components.AppNotFound, HTMLStencilElement {
    }
    var HTMLAppNotFoundElement: {
        prototype: HTMLAppNotFoundElement;
        new (): HTMLAppNotFoundElement;
    };
    interface HTMLAppPageElement extends Components.AppPage, HTMLStencilElement {
    }
    var HTMLAppPageElement: {
        prototype: HTMLAppPageElement;
        new (): HTMLAppPageElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-blog": HTMLAppBlogElement;
        "app-blog-post": HTMLAppBlogPostElement;
        "app-devtools": HTMLAppDevtoolsElement;
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-not-found": HTMLAppNotFoundElement;
        "app-page": HTMLAppPageElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppBlog {
        "match"?: MatchResults;
    }
    interface AppBlogPost {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface AppDevtools {
        "blogList"?: [];
        "blogPost"?: {};
        "page"?: string;
    }
    interface AppFooter {
        "entries"?: {};
        "footer"?: {};
    }
    interface AppHeader {
        "entries"?: {};
        "header"?: {};
    }
    interface AppHome {
        "history"?: RouterHistory;
    }
    interface AppNotFound {
    }
    interface AppPage {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-blog": AppBlog;
        "app-blog-post": AppBlogPost;
        "app-devtools": AppDevtools;
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-not-found": AppNotFound;
        "app-page": AppPage;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-blog": LocalJSX.AppBlog & JSXBase.HTMLAttributes<HTMLAppBlogElement>;
            "app-blog-post": LocalJSX.AppBlogPost & JSXBase.HTMLAttributes<HTMLAppBlogPostElement>;
            "app-devtools": LocalJSX.AppDevtools & JSXBase.HTMLAttributes<HTMLAppDevtoolsElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-not-found": LocalJSX.AppNotFound & JSXBase.HTMLAttributes<HTMLAppNotFoundElement>;
            "app-page": LocalJSX.AppPage & JSXBase.HTMLAttributes<HTMLAppPageElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
